CREATE TABLE STUDENT
(
ID INTEGER,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
GRADE VARCHAR(5),
EMAIL VARCHAR(20),
GUARDIAN_NAME VARCHAR(20),
AGE INTEGER,
BIRTH_DATE TIMESTAMP(6),
PRIMARY KEY (ID)
);